### ISSUE TITLE
Chrome and Edge don't display a page header by default

### ISSUE THREAD

**Issue by dogatana** [honkit/honkit#135] opened 2020-10-05 06:18 UTC
## Summary

Firefox works well, but Chorme and Edge don't.
We can see the header by scrolling up, but it's not good on the usability's point of view.
Any workarouds are most welcome!

- HonKit version: 3.6.6

## Step to reproduce

1. npx honkit build
2. npx honkit serve

- Link to code example: https://github.com/dogatana/header-shift.git

## Expected results

All browsers should show a page header by default.

## Actual results

see attached image.
![result](https://user-images.githubusercontent.com/12756480/95045408-f670d300-071c-11eb-8cd2-a2287b00be16.png)

- log

```
C:\Git\honkit-project\header-shift
> npx honkit build --log=debug
debug: readme found at README.md
debug: summary file found at SUMMARY.md
debug: cleanup folder "C:\Git\honkit-project\header-shift\_book"
info: 5 plugins are installed
info: 5 explicitly listed
info: plugin "highlight is loaded
info: plugin "search is loaded
info: plugin "lunr is loaded
info: plugin "fontsettings is loaded
info: plugin "theme-default is loaded
info: found 1 pages
info: found 3 asset files
debug: calling hook "config"
debug: calling hook "init"
debug: copy assets from theme C:\Git\honkit-project\header-shift\node_modules\@honkit\honkit-plugin-theme-default\_assets\website
debug: copy resources from plugin C:\Git\honkit-project\header-shift\node_modules\gitbook-plugin-fontsettings\assets
debug: copy resources from plugin C:\Git\honkit-project\header-shift\node_modules\gitbook-plugin-lunr\assets
debug: copy resources from plugin C:\Git\honkit-project\header-shift\node_modules\gitbook-plugin-search\assets
debug: copy resources from plugin C:\Git\honkit-project\header-shift\node_modules\gitbook-plugin-highlight\css
debug: copy asset ".gitignore"
debug: copy asset "package-lock.json"
debug: copy asset "package.json"
debug: calling hook "finish:before"
debug: calling hook "finish"
debug: write search index
info: >> generation finished with success in 0.5s !
```

**Comment by azu** [comment] 2020-10-05 06:48
I've confirmed.

Original GitBook's theme may intent to scroll to chapter header. 
But, I agree that this behavior is unexpected.

**Comment by dogatana** [comment] 2020-10-05 09:54
Thanks for info.

I changed function init in navigation.js as following.

```
    // Prepare current page
    preparePage(true);
```

Now Chrome and Edge now work well, but IE11 still doesn't.

If Safari on macOS works, this seems to be a tentative solution.

**Comment by azu** [comment] 2020-10-29 14:05
Scroll Behavior

- First: start 0,0
- [ ] Reload Page: preserve scroll - currently reset position
- Forward/Backward page: scroll the first chapter

This issue is caused by `Element.forus()`

https://github.com/honkit/honkit/blob/1a9cbf96860f03237d09e99a3a8dd6bae99d16c3/packages/@honkit/theme-default/src/js/theme/navigation.js#L369

`preventScroll` option will resolve this issue.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

**Comment by azu** [comment] 2020-10-29 14:15
fixed in https://github.com/honkit/honkit/commit/4fb9cd361d0ae3b40394b632050d77f248ca051d

Can you confirm it?
https://honkit.netlify.app/

**Closed** 2020-10-29 14:15 UTC
Labels: Type: Theme

**Comment by dogatana** [comment] 2020-11-27 05:52
Sorry for the late response.
Thank you very much for the update.

I've confirmed.
I applied this change to `@dogatana/honkit-plugin-theme-default-fa5` too and it works file on major browses of Windows 10.

- IE11 11.1139.18362.0
- Edge 87.0.664.47
- Firefox 83.0
- Chrome 87.0.4280.66
